notifications:
  email: false

language: cpp
compiler: gcc
dist: jammy
sudo: required

#https://github.com/travis-ci/travis-ci/issues/6730
#branches:
#  only:
#    - master


git:
  depth: 1

before_install:
  # Update informations about new available packages 
  - sudo apt-get update -qq

install:
  # For Qt
  - sudo apt-get install -qq qt6-base qt6-image-formats-plugins qt6-svg

before_script:
  # Set up the new Qt environment
  - QTDIR="/opt/qt56"
  - PATH="$QTDIR/bin:$PATH"
  - source /opt/qt56/bin/qt56-env.sh

  # Build Leviathan version.h file
  - printf '#ifndef VERSION_H\n' > src/version.h
  - printf '#define VERSION_H\n' >> src/version.h
  - printf '#define LEVIATHAN_VERSION \\\n' >> src/version.h
  - |
    if [[ -z "$TRAVIS_TAG" ]]; then
        printf "$TRAVIS_TAG - " >> src/version.h
    fi 
  - git log -1 --format=%ci >> src/version.h
  - printf '\n#endif // VERSION_H' >> src/version.h

script:
  # - g++ --version
  # - qmake --version
  - cd src
  - qmake Leviathan.pro CONFIG+=release
  - make -j2

#after_success:
  # Pack everything in a zip
  - tar -czf LeviathanLinux64-automated-${TRAVIS_TAG}.zip Leviathan

deploy:
  provider: releases
  name: $TRAVIS_TAG
  api_key:
    secure: $GITHUB_AUTH
  file: LeviathanLinux64-automated-${TRAVIS_TAG}.zip
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
