shallow_clone: true
clone_depth: 1

branches:
  only:
    - master

image:
  - Visual Studio 2019
  - Ubuntu
  - macos-bigsur

install:
  # Build Leviathan version file
  - python appveyor_generateversion.py

for:
  - # Windows
    matrix:
      only:
      - image: Visual Studio 2019

    environment:
      # Set Qt toolkit path
      - set QTOOLS=C:\Qt\Tools\mingw900_64\bin
      - set QTDIR=C:\Qt\6.4.2\mingw_64 # required as is

    before_build:
      - cmd /c ver
      - gcc --version
      - qmake --version
      - cmake --version
      - python --version

    build_script:
      - cd src
      - mkdir deploy64

      - set PATH=%QTOOLS%;%QTDIR%\bin;%PATH%
      - mingw32-make clean
      - del Makefile*
      - del .qmake.stash

      - qmake Leviathan.pro CONFIG+=release
      - mingw32-make -j%NUMBER_OF_PROCESSORS%

    after_build:
      - copy /Y release\Leviathan.exe deploy64

      # Prepare the libraries and the other files to deploy  
      - call %QTDIR%\bin\windeployqt.exe --force --compiler-runtime --no-translations --no-opengl-sw --no-system-d3d-compiler --no-quick-import --no-virtualkeyboard deploy64
      # windeployqt only copies the required Qt dlls, not the c++ ones, even if i added --compiler-runtime
      - copy /Y "%QTOOLS%\libstdc++-6.dll" deploy64
      - copy /Y "%QTOOLS%\libgcc_s_seh-1.dll" deploy64
      - copy /Y "%QTOOLS%\libwinpthread-1.dll" deploy64
      - copy /Y "%QTOOLS%\libgomp*.dll" deploy64		# we need the OpenMP libraries

      # Copy extra required libs
      - copy /Y ..\winlibs\64\zlib.dll deploy64

      # Pack everything in a zip
      - 7z a LeviathanWin64-automated-%APPVEYOR_REPO_TAG_NAME%.zip .\deploy64\*

    artifacts:
      - path: src/LeviathanWin64-automated-$(APPVEYOR_REPO_TAG_NAME).zip
        name: binpkg-x86_64

    deploy:
        release: $(APPVEYOR_REPO_TAG_NAME)
        description: 'Windows build (x86_64 arch)'
        provider: GitHub
        auth_token:
          secure: Hb86lGnsXj56Q4P+Y1pRpovrFJ5Qa/Bn6+Zr9L6Maqmlx978GU3hFhWcqpTD326w
        artifact: binpkg-x86_64
        draft: false
        prerelease: false
        on:
          branch: master                 # release from master branch only
          appveyor_repo_tag: true        # deploy on tag push only


  - # Linux build
    matrix:
      only:
      - image: Ubuntu

    environment:
      # Set Qt toolkit path
      - export QTDIR=${HOME}/Qt/6.2/gcc_64
      - export PATH="${QTDIR}/bin:$PATH"

    before_build:
      - lsb_release -d
      - gcc --version
      - qmake --version
      - cmake --version
      - python --version

    build_script:
      - cd src
      - qmake Leviathan.pro CONFIG+=release
      - make -j"$(nproc)"

    after_build:
      # Pack everything in a zip
      - tar -czf LeviathanLinux64-automated-${APPVEYOR_REPO_TAG_NAME}.zip Leviathan
    
    artifacts:
      - path: src/LeviathanLinux64-automated-$(APPVEYOR_REPO_TAG_NAME).zip
        name: binpkg-x86_64

    deploy:
      release: $(APPVEYOR_REPO_TAG_NAME)
      description: 'Linux build (x86_64 arch)'
      provider: GitHub
      auth_token:
        secure: Hb86lGnsXj56Q4P+Y1pRpovrFJ5Qa/Bn6+Zr9L6Maqmlx978GU3hFhWcqpTD326w
      artifact: binpkg-x86_64
      draft: false
      prerelease: false
      on:
        branch: master                 # release from master branch only
        appveyor_repo_tag: true        # deploy on tag push only


  - # MacOS
    matrix:
      only:
      - image: macos-bigsur

    environment:
      # Set Qt toolkit path
      - export QTDIR=${HOME}/Qt/6.2/macos
      - export PATH="${QTDIR}/bin:$PATH"

    before_build:
      - sw_vers
      - gcc --version
      - qmake --version
      - cmake --version
      - python --version

    build_script:
      - cd src
      - qmake Leviathan.pro CONFIG+=release
      - make -j"$(nproc)"

    after_build:
      # Pack everything in a zip
      - zip -r LeviathanMacOSx86_64-automated-${APPVEYOR_REPO_TAG_NAME}.zip Leviathan
    
    artifacts:
      - path: src/LeviathanMacOSx86_64-automated-$(APPVEYOR_REPO_TAG_NAME).zip
        name: binpkg-x86_64

    deploy:
      release: $(APPVEYOR_REPO_TAG_NAME)
      description: 'MacOS build (x86_64 arch)'
      provider: GitHub
      auth_token:
        secure: Hb86lGnsXj56Q4P+Y1pRpovrFJ5Qa/Bn6+Zr9L6Maqmlx978GU3hFhWcqpTD326w
      artifact: binpkg-x86_64
      draft: false
      prerelease: false
      on:
        branch: master                 # release from master branch only
        appveyor_repo_tag: true        # deploy on tag push only
